services:
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/code

  database:
    extends:
      file: docker-compose.yml
      service: database

  inference:
    extends:
      file: docker-compose.yml
      service: inference

configs:
  qdrant_config:
    content: |
      log_level: DEBUG

networks:
  app-network:
    driver: bridge
