services:
  lhscr-frontend:
    extends:
      file: docker-compose.yml
      service: lhscr-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules

  lhscr-backend:
    extends:
      file: docker-compose.yml
      service: lhscr-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development

  lhscr-vector-db:
    extends:
      file: docker-compose.yml
      service: lhscr-vector-db

  inference:
    extends:
      file: docker-compose.yml
      service: inference

  embeddings:
    extends:
      file: docker-compose.yml
      service: embeddings

configs:
  qdrant_config:
    content: |
      log_level: DEBUG
